language: python
dist: focal

matrix:
  include:
    - python: 3.8
      env: TOXENV=lint
    - python: 3.8
      env: TOXENV=cover
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.5
      env: TOXENV=py35-uvloop
    - python: 3.6
      env: TOXENV=py36-uvloop
    - python: 3.7
      env: TOXENV=py37-uvloop
    - python: 3.8
      env: TOXENV=py38-uvloop
install:
  - "sudo apt update && sudo apt install cargo -y"
  - "pip install cryptography"
  - "mkdir -p /tmp/certs /tmp/local-certs /tmp/client-certs"
  - "tests/mkcerts.py -o /tmp/certs -D localhost"
  - "tests/mkcerts.py -o /tmp/local-certs -D localhost"
  - "tests/mkcerts.py -o /tmp/client-certs -D client1"
  - "sudo mkdir -p /usr/local/share/ca-certificates/test"
  - "sudo install -m 644 -o root -g root /tmp/certs/ca.pem /usr/local/share/ca-certificates/test/test-ca.crt"
  - "sudo update-ca-certificates"
  - "pip install tox"
script:
  - tox
